<%
  platforms = %w(centos-7.4 centos-6)
  use_git = 'true'
  use_json = 'true'
%>
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  sudo: true
<% if use_json == 'true' %>
  format: json
  output: results.json
<% end %>

platforms:
<% platforms.each do |plat| %>
- name: <%= plat %>
  verifier:
      inspec_tests:
      - name: <%= plat %>
      <% if use_git == 'false' %>
        path: test/integration/<%= plat %>/inspec
      <% else %>
        git: https://github.com/djhaynes/inspec-profile-disa_stig-el7.git
        branch: dev
      <% end %>
      attrs:
      - attributes.dev.yml
<% end %>

suites:
  - name: default
    run_list:
      - recipe[stig::core_packages]
      - recipe[auditd]
      - recipe[stig::auditd]
      - recipe[stig::auditd_rules]
      - recipe[stig::fstab_tmp]
      - recipe[stig::tcp_wrappers]
      - recipe[stig::boot_settings]
      - recipe[stig::proc_hard]
      - recipe[stig::cis]
      - recipe[stig::avahi_daemon]
      - recipe[stig::ipv6]
      - recipe[stig::dhcp]
      - recipe[stig::mail_transfer_agent]
      - recipe[stig::hosts]
      - recipe[stig::rsyslog]
      - recipe[stig::syslog_ng]
      - recipe[logrotate::global]
      - recipe[stig::sshd_config]
      - recipe[stig::system_auth]
      - recipe[stig::login_defs]
      - recipe[stig::login_banner]
      - recipe[stig::file_permissions]
      - recipe[stig::audits]
      - recipe[stig::audit_scripts]
      - recipe[stig::su_restriction]
      - recipe[stig::aide]
      - recipe[stig::screen]
    attributes:
      "auditd" :
        "ruleset" : "stig"

  - name: vanilla
    run_list:
 
